replicaCount: 1

image:
  repository: docker.io/nginxdemos/hello
  tag: "0.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

nodeSelector: {}
tolerations: []
affinity: {}
